/**
 * Attachment service.
 *
 * Uploads are streamed to disk with a content-addressed name, so re-uploading
 * the same bytes does not consume space twice. Two safety checks matter:
 *
 *  * the stored name is generated by the server, never derived from the
 *    client-supplied filename, which removes the entire path-traversal class of
 *    attack;
 *  * the file's magic bytes are checked against the declared MIME type, so a
 *    renamed executable is rejected rather than served back later.
 */

import { createHash, randomUUID } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, rename, rm, stat } from 'node:fs/promises';
import { dirname, extname, join, normalize, resolve, sep } from 'node:path';
import { pipeline } from 'node:stream/promises';
import type { Readable } from 'node:stream';
import { MIME_SIGNATURES, MUTABLE_MIME_TYPES, type IssueAttachment } from '@tracker/shared';
import { badRequest, notFound, payloadTooLarge } from '../errors.ts';
import { nowIso } from '../lib/time.ts';
import type { Services } from './context.ts';

export interface UploadInput {
  issueId: number;
  commentId?: number | null;
  /** Client-supplied name, used for display only. */
  filename: string;
  declaredMimeType: string;
  stream: Readable;
  /** Required when the request declared a Content-Length. */
  expectedSize?: number;
}

export class AttachmentService {
  private readonly services: Services;

  constructor(services: Services) {
    this.services = services;
  }
  private get uploadDir(): string {
    return this.services.config.uploadDir;
  }

  /**
   * Store an uploaded file and register it against the issue.
   *
   * The file is buffered to a temporary path and only moved into place once the
   * size and signature checks pass, so a rejected upload never leaves a partial
   * file behind.
   */
  async upload(input: UploadInput, actorId: number): Promise<IssueAttachment> {
    const issue = this.services.db.get<{ id: number; project_id: number }>(
      'SELECT id, project_id FROM issues WHERE id = ?',
      [input.issueId],
    );
    if (!issue) throw notFound('Issue', input.issueId);

    const mimeType = this.normaliseMimeType(input.declaredMimeType, input.filename);
    if (!MUTABLE_MIME_TYPES.has(mimeType)) {
      throw badRequest(`Files of type "${mimeType}" cannot be uploaded`, { mimeType });
    }

    if (input.expectedSize !== undefined && input.expectedSize > this.services.config.maxUploadBytes) {
      throw payloadTooLarge(
        `File exceeds the ${Math.floor(this.services.config.maxUploadBytes / (1024 * 1024))}MB limit`,
      );
    }

    await mkdir(join(this.uploadDir, 'blobs'), { recursive: true });

    const tempPath = join(this.uploadDir, 'blobs', `tmp-${randomUUID()}`);
    const hash = createHash('sha256');
    let size = 0;
    const limit = this.services.config.maxUploadBytes;

    try {
      // Count and hash while streaming so an oversized or lying Content-Length
      // is caught without buffering the whole body in memory.
      input.stream.on('data', (chunk: Buffer) => {
        size += chunk.length;
        hash.update(chunk);
      });

      await pipeline(input.stream, createWriteStream(tempPath));

      if (size > limit) {
        throw payloadTooLarge(`File exceeds the ${Math.floor(limit / (1024 * 1024))}MB limit`);
      }
      if (size === 0) throw badRequest('The uploaded file is empty');

      const checksum = hash.digest('hex');

      // Content-addressed name: identical bytes reuse one file on disk.
      const extension = extname(input.filename).slice(0, 12).replace(/[^A-Za-z0-9.]/g, '');
      const storedName = join('blobs', `${checksum}${extension}`);
      const finalPath = this.resolveStoredPath(storedName);

      const existing = await stat(finalPath).catch(() => null);
      if (existing) {
        await rm(tempPath, { force: true });
      } else {
        await mkdir(dirname(finalPath), { recursive: true });
        try {
          await rename(tempPath, finalPath);
        } catch (error) {
          // A parallel upload of identical bytes may have won the race; the
          // blob we need exists either way.
          const code = (error as NodeJS.ErrnoException).code;
          if (code !== 'EEXIST' && code !== 'EPERM' && code !== 'EACCES') throw error;
          await rm(tempPath, { force: true });
        }
      }

      const id = Number(
        this.services.db.run(
          `INSERT INTO attachments
             (issue_id, comment_id, filename, stored_name, mime_type, size_bytes, checksum, uploaded_by)
           VALUES (?,?,?,?,?,?,?,?)`,
          [
            input.issueId,
            input.commentId ?? null,
            this.sanitiseFilename(input.filename),
            storedName,
            mimeType,
            size,
            checksum,
            actorId,
          ],
        ).lastInsertRowid,
      );

      this.services.activity.record({
        issueId: input.issueId,
        projectId: Number(issue.project_id),
        actorId,
        type: 'attachment.added',
        summary: `attached ${this.sanitiseFilename(input.filename)}`,
        metadata: { attachmentId: id, sizeBytes: size, mimeType },
      });

      this.services.audit.record(
        {
          action: 'attachment.uploaded',
          entityType: 'attachment',
          entityId: id,
          projectId: Number(issue.project_id),
          actorId,
          after: { issueId: input.issueId, filename: input.filename, sizeBytes: size, mimeType },
        },
        {},
      );

      this.services.realtime.publish({
        event: 'attachment.added',
        projectId: Number(issue.project_id),
        issueId: input.issueId,
        data: { attachmentId: id, filename: input.filename },
      });

      return this.getById(id);
    } catch (error) {
      // Never leave a temp file behind, whatever went wrong.
      await rm(tempPath, { force: true }).catch(() => undefined);
      throw error;
    }
  }

  listForIssue(issueId: number): IssueAttachment[] {
    return this.services.db
      .all<Record<string, unknown>>(
        'SELECT * FROM attachments WHERE issue_id = ? ORDER BY created_at ASC, id ASC',
        [issueId],
      )
      .map((row) => this.mapAttachment(row));
  }

  getById(attachmentId: number): IssueAttachment {
    const row = this.services.db.get<Record<string, unknown>>('SELECT * FROM attachments WHERE id = ?', [
      attachmentId,
    ]);
    if (!row) throw notFound('Attachment', attachmentId);
    return this.mapAttachment(row);
  }

  /**
   * Resolve an attachment to an absolute path on disk.
   *
   * The stored name is re-derived from the checksum and re-checked against the
   * upload root, so even a corrupted database row cannot escape the directory.
   */
  resolveDownloadPath(attachmentId: number): { path: string; attachment: IssueAttachment } {
    const attachment = this.getById(attachmentId);

    const expected = join('blobs', `${attachment.checksum}${extname(attachment.storedName)}`);
    if (attachment.storedName !== expected) {
      throw badRequest('Attachment record is inconsistent and cannot be served');
    }

    const root = resolve(this.uploadDir);
    const full = resolve(root, attachment.storedName);
    if (!full.startsWith(root + sep)) {
      throw badRequest('Attachment path escapes the upload directory');
    }

    return { path: full, attachment };
  }

  /** Stream an attachment to a writable response stream. */
  async stream(attachmentId: number, sink: NodeJS.WritableStream): Promise<number> {
    const { path } = this.resolveDownloadPath(attachmentId);
    await pipeline(createReadStream(path), sink);
    const info = await stat(path);
    return info.size;
  }

  remove(attachmentId: number, actorId: number): void {
    const attachment = this.getById(attachmentId);
    const projectId = this.services.db.scalar<number>('SELECT project_id FROM issues WHERE id = ?', [
      attachment.issueId,
    ]);

    this.services.db.run('DELETE FROM attachments WHERE id = ?', [attachmentId]);

    // The blob is content-addressed, so it may be shared by another row; only
    // delete the file once no other attachment references the checksum.
    const stillReferenced = Number(
      this.services.db.scalar<number>('SELECT COUNT(*) AS c FROM attachments WHERE checksum = ?', [
        attachment.checksum,
      ]) ?? 0,
    );
    if (stillReferenced === 0) {
      const { path } = this.resolveDownloadPath(attachmentId);
      void rm(path, { force: true });
    }

    this.services.activity.record({
      issueId: attachment.issueId,
      projectId: Number(projectId ?? 0),
      actorId,
      type: 'attachment.removed',
      summary: `removed ${attachment.filename}`,
      metadata: { attachmentId },
    });

    this.services.audit.record(
      {
        action: 'attachment.deleted',
        entityType: 'attachment',
        entityId: attachmentId,
        projectId: projectId === null || projectId === undefined ? null : Number(projectId),
        actorId,
        before: { filename: attachment.filename, sizeBytes: attachment.sizeBytes },
      },
      {},
    );

    this.services.realtime.publish({
      event: 'attachment.added',
      issueId: attachment.issueId,
      data: { attachmentId, removed: true },
    });
  }

  /**
   * Verify the leading bytes against the declared MIME type. Returns true when
   * the type cannot be checked (text formats have no reliable signature).
   */
  verifySignature(path: string, mimeType: string): Promise<boolean> {
    const signature = MIME_SIGNATURES.find(([type]) => type === mimeType);
    if (!signature) return Promise.resolve(true);

    return new Promise((resolvePromise) => {
      const stream = createReadStream(path, { start: 0, end: 7 });
      const chunks: Buffer[] = [];
      // A read stream in binary mode yields Buffers, but the type allows strings.
      stream.on('data', (chunk: string | Buffer) => {
        chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk);
      });
      stream.on('end', () => {
        const head = Buffer.concat(chunks);
        const [, magic] = signature;
        const matches = magic.every((byte, index) => head[index] === byte);
        resolvePromise(matches);
      });
      stream.on('error', () => resolvePromise(false));
    });
  }

  /** Absolute path for a stored name, guarded against traversal. */
  private resolveStoredPath(storedName: string): string {
    const root = resolve(this.uploadDir);
    const full = resolve(root, normalize(storedName));
    if (!full.startsWith(root + sep)) {
      throw badRequest('Attachment path escapes the upload directory');
    }
    return full;
  }

  /** Display name only: strip any directory component a client supplied. */
  private sanitiseFilename(filename: string): string {
    const base = filename.split(/[/\\]/).pop() ?? 'file';
    // Remove control characters (including NUL and newlines) that a crafted
    // filename could use to confuse downstream logging or header construction.
    const cleaned = base.replace(/[\u0000-\u001f\u007f]/g, '').trim();
    return cleaned.length > 0 ? cleaned.slice(0, 200) : 'file';
  }

  private normaliseMimeType(declared: string, filename: string): string {
    const value = (declared || '').split(';')[0]?.trim().toLowerCase() ?? '';
    if (value.length > 0) return value;
    // Fall back to the extension for clients that send no usable type.
    const ext = extname(this.sanitiseFilename(filename)).toLowerCase();
    const byExtension: Record<string, string> = {
      '.png': 'image/png',
      '.jpg': 'image/jpeg',
      '.jpeg': 'image/jpeg',
      '.gif': 'image/gif',
      '.webp': 'image/webp',
      '.pdf': 'application/pdf',
      '.txt': 'text/plain',
      '.log': 'text/x-log',
      '.csv': 'text/csv',
      '.json': 'application/json',
      '.zip': 'application/zip',
    };
    return byExtension[ext] ?? 'application/octet-stream';
  }

  private mapAttachment(row: Record<string, unknown>): IssueAttachment {
    return {
      id: Number(row.id) as IssueAttachment['id'],
      issueId: Number(row.issue_id) as IssueAttachment['issueId'],
      commentId: row.comment_id === null ? null : (Number(row.comment_id) as IssueAttachment['commentId']),
      filename: String(row.filename),
      storedName: String(row.stored_name),
      mimeType: String(row.mime_type),
      sizeBytes: Number(row.size_bytes),
      checksum: String(row.checksum),
      uploadedBy: Number(row.uploaded_by) as IssueAttachment['uploadedBy'],
      createdAt: String(row.created_at ?? nowIso()),
    };
  }
}